line-length = 88

[lint]
preview = true
extend-select = [
  "B",
  "ERA",
  "I",
  "PLE",
  "PLW",
  "W",
]
extend-ignore = [
  "PLW1510",
  "PLW2901",
]

[lint.isort]
split-on-trailing-comma = false

[format]
line-ending = "lf"
skip-magic-trailing-comma = true

[lint.per-file-ignores]
"utils/flatpak-builder-to-bst.py" = [
  "PLR0133",
  "UP022",
  "TRY002",
  "RET504",
  "BLE001",
  "PLR1704",
  "SIM115",
]
