line-length = 88

[lint]
preview = true
extend-select = [
  "B",
  "ERA",
  "I",
  "PLE",
  "PLW",
  "W",
]
extend-ignore = [
  "PLW1510",
  "PLW2901",
  "too-many-statements-in-try-clause",
]

[lint.isort]
split-on-trailing-comma = false

[format]
line-ending = "lf"
skip-magic-trailing-comma = true

