name: freedesktop-sdk

min-version: 2.5

aliases:
  (@): include/_private/aliases.yml

(@):
- include/_private/mirrors.yml
- include/runtime.yml

element-path: elements

fatal-warnings:
- overlaps
- unaliased-url

variables:
  (@):
  - include/_private/arch.yml
  - include/repo_branches.yml

  branch: '%{freedesktop-sdk-flatpak-branch}'
  branch-extra: '%{freedesktop-sdk-flatpak-branch-extra}'

  build-root: '/buildstream-build'
  source-date-epoch: '1320937200'

environment:
  (@): include/_private/environment.yml

  SOURCE_DATE_EPOCH: '%{source-date-epoch}'

  G_SLICE: always-malloc
  OMP_NUM_THREADS: "4"
  GOMAXPROCS: "%{max-jobs}"
  CARGO_BUILD_JOBS: "%{max-jobs}"
  GOPATH: "%{build-root}"

environment-nocache:
  (>):
  - G_SLICE
  - OMP_NUM_THREADS
  - GOMAXPROCS
  - CARGO_BUILD_JOBS

split-rules:
  (@): include/_private/split-rules.yml

plugins:
  - origin: local
    path: plugins/sources
    sources:
    - ostree_mirror

  - origin: local
    path: plugins/elements
    elements:
    - collect_initial_scripts

  - origin: junction
    junction: plugins/buildstream-plugins.bst
    elements:
    - autotools
    - cmake
    - make
    - meson
    sources:
    - docker
    - patch

  - origin: junction
    junction: plugins/buildstream-plugins-community.bst
    elements:
    - check_forbidden
    - collect_integration
    - collect_manifest
    - flatpak_image
    - flatpak_repo
    - makemaker
    - modulebuild
    - pyproject
    sources:
    - cargo2
    - cpan
    - git_module
    - git_repo
    - go_module
    - ostree
    - patch_queue
    - pypi
    - zip

options:
  bootstrap_build_arch:
    type: arch
    description: Architecture
    variable: bootstrap_build_arch
    values:
    - aarch64
    - x86_64
    - ppc64le
    - riscv64
    - loongarch64

  target_arch:
    type: arch
    description: Architecture
    variable: target_arch
    values:
    - aarch64
    - i686
    - x86_64
    - ppc64le
    - ppc64
    - riscv64
    - loongarch64

  minimal_vm:
    type: flags
    description: Parts to include in minimal vm builds (firmware, locale).
    values:
    - firmware
    - locale
    default:
    - locale

  full_abi_diff:
    type: bool
    description: Forces full ABI diff on
    variable: full_abi_diff
    default: False

  x86_64_v3:
    type: bool
    description: Enable x86_64-v3 (EXPERIMENTAL)
    default: False

  prod_keys:
    type: bool
    description: Use production boot keys
    default: False

artifacts:
- url: https://cache.freedesktop-sdk.io:11001
  connection-config:
    keepalive-time: 60

source-caches:
- url: https://cache.freedesktop-sdk.io:11001
  connection-config:
    keepalive-time: 60

sandbox:
  build-arch: '%{target_arch}'

elements:
  autotools:
    (@): include/_private/autotools-conf.yml
  cmake:
    (@): include/_private/cmake-conf.yml
  meson:
    (@): include/_private/meson-conf.yml
  makemaker:
    variables:
      strip-binaries: ''
  modulebuild:
    variables:
      strip-binaries: ''

sources:
  git_repo:
    (@): include/_private/git_repo-conf.yml
  pypi:
    (@): include/_private/pypi.yml
  cpan:
    (@): include/_private/cpan.yml
  cargo:
    (@): include/_private/cargo.yml
  cargo2:
    (@): include/_private/cargo2.yml



junctions:
  # We can declare these junctions as "internal" because we only use them for build dependencies
  # Therefore we know they can't collide with elements in dependant projects.
  internal:
  - abi/compat-x86_64.bst
  - abi/reference-abi.bst
  - cross-compilers/freedesktop-sdk-aarch64.bst
  - cross-compilers/freedesktop-sdk-i686.bst
  - cross-compilers/freedesktop-sdk-riscv64.bst
  - cross-compilers/freedesktop-sdk-loongarch64.bst
  - plugins/buildstream-plugins.bst
  - plugins/buildstream-plugins-community.bst
