version = 1

[[annotations]]
path = [
    "*",
    ".*",
    "keys/*",
    "ostree-gpg/**",
    "patches/**/*.patch",
    "patches/**/*.diff",
    "files/font-conf/**",
    "files/fontconfig/**",
]
SPDX-FileCopyrightText = "Freedesktop-SDK Developers"
SPDX-License-Identifier = "MIT"
