# SPDX-FileCopyrightText: Freedesktop-SDK Developers
# SPDX-License-Identifier: MIT

variables:
  prefix: '/usr/lib/%{gcc_triplet}/codecs-extra'
  libdir: '%{prefix}/lib'
  lib: 'lib'
  libheif-libde265-plugin: 'ON'
  libheif-libx265-plugin: 'ON'
