# SPDX-FileCopyrightText: Freedesktop-SDK Developers
# SPDX-License-Identifier: MIT

sources:
- kind: git_repo
  url: github:pkgconf/pkgconf.git
  track: pkgconf-*
  exclude:
  - pkgconf-*.9*.9*
  ref: pkgconf-3.0.5-0-g3086e5dfc16b8cf9a9b66f6827868af4aa85e9bd
