# SPDX-FileCopyrightText: Freedesktop-SDK Developers
# SPDX-License-Identifier: MIT

sources:
- kind: git_repo
  url: github:pkgconf/pkgconf.git
  track: pkgconf-*
  exclude:
  - pkgconf-*.9*.9*
  ref: pkgconf-3.0.8-0-gc942f2ec2f7e2b1e4d874d694cd92648a70e5c6e
