# SPDX-FileCopyrightText: Freedesktop-SDK Developers
# SPDX-License-Identifier: MIT

sources:
- kind: git_repo
  url: github:pkgconf/pkgconf.git
  track: pkgconf-*
  exclude:
  - pkgconf-*.9*.9*
  ref: pkgconf-3.0.7-0-g0c9e506b64124d8727b68d8af0ed73739e66e2ba
