# SPDX-FileCopyrightText: Freedesktop-SDK Developers
# SPDX-License-Identifier: MIT

auth            sufficient      pam_rootok.so
auth            include         system-auth
account         include         system-auth
password        include         system-auth
session         include         system-auth
