variables:
  prefix: "/usr/lib/%{gcc_triplet}/GL/default"
  lib: "lib"
  debugdir: "/usr/lib/debug"
  debugdatadir: "%{debugdir}%{prefix}"
  conf-libtool-force-dlsearch: ""
  local_ldflags: "-Wl,-rpath=%{libdir}"
