[Partition]
Type=root
Label=root
Format=ext4

# the result of "$(uuidgen -s --namespace "%{uuidnamespace}" --name root)"
# with uuidnamespace=df2427db-01ec-4c99-96b1-be3edb3cd9f6
UUID=9e71ad99-5ddc-5b20-8b9c-f3f6b4e570e1
CopyFiles=/:/
SizeMinBytes=8G
GrowFileSystem=yes
