#!/usr/bin/env python3
# SPDX-FileCopyrightText: Freedesktop-SDK Developers
# SPDX-License-Identifier: MIT
"""
Replace bootstrap/ runtime dependencies with components/ equivalents.

This script:
  1. Generates new `components/<name>.bst` filter elements for bootstrap
     elements that components/ needs at runtime but which do not yet have a
     components/ wrapper (modeled on components/pcre2.bst).
  2. Rewrites `depends:` and `runtime-depends:` lists in elements under
     components/ so that no bootstrap/ element remains in the runtime
     dependency set.

`build-depends:` lists are never modified: bootstrap elements are still used
at build time, we only change what ends up in the runtime system.
"""

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
COMPONENTS_DIR = REPO / "elements" / "components"


def component_files():
    """All element files under components/ (including _private/)."""
    files = sorted(COMPONENTS_DIR.glob("*.bst"))
    files += sorted((COMPONENTS_DIR / "_private").glob("*.bst"))
    return files

# Mapping of bootstrap/ runtime deps to their replacement.
#
# Two kinds of replacement:
#   - public-stacks/runtime-minimal.bst: bootstrap/glibc.bst (the stack
#     already pulls in glibc, symlinks, gcc-libs and utf-locale)
#   - components/<name>.bst: either an existing components/ element, or one
#     generated by this script (see GENERATED below).
REPLACEMENTS = {
    "bootstrap/bash.bst": "components/bash.bst",
    "bootstrap/binutils.bst": "components/binutils.bst",
    "bootstrap/bzip2.bst": "components/bzip2.bst",
    "bootstrap/coreutils.bst": "components/coreutils.bst",
    "bootstrap/debugedit.bst": "components/debugedit.bst",
    "bootstrap/diffutils.bst": "components/diffutils.bst",
    "bootstrap/elfutils.bst": "components/elfutils.bst",
    "bootstrap/file.bst": "components/file.bst",
    "bootstrap/findutils.bst": "components/findutils.bst",
    "bootstrap/gawk.bst": "components/gawk.bst",
    "bootstrap/glibc.bst": "public-stacks/runtime-minimal.bst",
    "bootstrap/gnu-config.bst": "components/gnu-config.bst",
    "bootstrap/grep.bst": "components/grep.bst",
    "bootstrap/gzip.bst": "components/gzip.bst",
    "bootstrap/libxcrypt.bst": "components/libxcrypt.bst",
    "bootstrap/make.bst": "components/make.bst",
    "bootstrap/ncurses.bst": "components/ncurses.bst",
    "bootstrap/pcre2.bst": "components/pcre2.bst",
    "bootstrap/sed.bst": "components/sed.bst",
    "bootstrap/stripper.bst": "components/stripper.bst",
    "bootstrap/symlinks.bst": "components/symlinks.bst",
    "bootstrap/xxhash.bst": "components/xxhash.bst",
    "bootstrap/xz.bst": "components/xz.bst",
    "bootstrap/zlib-ng.bst": "components/zlib-ng.bst",
    "bootstrap/zstd.bst": "components/zstd.bst",
}

# New filter elements to generate, modeled on components/pcre2.bst.
# bootstrap/X.bst is wrapped so that its runtime deps come from the
# components/ set instead of the bootstrap/ set.
GENERATED = {
    "bash": "Bash: The GNU Bourne Again shell.",
    "coreutils": "Coreutils: Basic GNU file, shell and text utilities.",
    "debugedit": "debugedit: Tool for editing debuginfo section in ELF files.",
    "gnu-config": "GNU config: GNU config.guess and config.sub test suite.",
    "libxcrypt": "libxcrypt: Modern implementation of the crypt password hashing library.",
    "ncurses": "ncurses: Library functions for terminal-independent applications.",
    "symlinks": "Symlinks: Common symbolic links for the system.",
    "zlib-ng": "zlib-ng: High-speed drop-in replacement for zlib.",
}

HEADER = """# SPDX-FileCopyrightText: Freedesktop-SDK Developers
# SPDX-License-Identifier: MIT

kind: filter
description: |
  {desc}

# This element wraps `bootstrap/{name}.bst` to remove the dependency on other
# bootstrap elements, to avoid bringing in the whole bootstrap set.

build-depends:
- bootstrap/{name}.bst

runtime-depends:
- public-stacks/runtime-minimal.bst
"""

# Top-level dependency lists that are runtime deps (directly or transitively).
RUNTIME_LIST_RE = re.compile(r"^(runtime-depends|depends):")
# A top-level key line ends dependency-list parsing.
TOP_LEVEL_KEY_RE = re.compile(r"^[a-zA-Z][\w-]*:")
# A list entry line: "- bootstrap/xxx.bst" (possibly followed by a comment)
ENTRY_RE = re.compile(r"^(\s*)- (bootstrap/[a-z0-9./_-]+\.bst)(\s+#.*)?$")
# Any list entry line (starts with "-")
LIST_ENTRY_RE = re.compile(r"^\s*- ")


def process_file(path: Path, dry_run: bool):
    """Rewrite bootstrap/ refs in runtime dep lists.

    Returns (changes, new_lines) where changes is a list of human-readable
    change descriptions and new_lines is the post-replacement file content.
    """
    lines = path.read_text().splitlines(keepends=False)
    changes = []
    in_runtime_list = False
    out = []

    for line in lines:
        if TOP_LEVEL_KEY_RE.match(line):
            in_runtime_list = bool(RUNTIME_LIST_RE.match(line))
        elif in_runtime_list and not LIST_ENTRY_RE.match(line) and line.strip() and not line.strip().startswith("#"):
            # A non-list, non-comment line: the list has ended.
            in_runtime_list = False
        if in_runtime_list:
            m = ENTRY_RE.match(line)
            if m:
                indent, ref = m.group(1), m.group(2)
                if ref in REPLACEMENTS:
                    new = f"{indent}- {REPLACEMENTS[ref]}"
                    changes.append(f"{path.name}: {ref} -> {REPLACEMENTS[ref]}")
                    out.append(new)
                    continue
        out.append(line)

    if changes and not dry_run:
        path.write_text("\n".join(out) + "\n")
    return changes, out


def generate_filters(dry_run: bool) -> list[str]:
    results = []
    for name, desc in GENERATED.items():
        target = COMPONENTS_DIR / f"{name}.bst"
        if target.exists():
            results.append(f"{name}: already exists, skipped")
            continue
        content = HEADER.format(name=name, desc=desc)
        if not dry_run:
            target.write_text(content)
        results.append(f"{name}: generated {target.relative_to(REPO)}")
    return results


def scan_for_bootstrap(lines: list[str], name: str) -> list[str]:
    """Return bootstrap/ refs found in runtime dep lists of the given lines."""
    problems = []
    in_runtime_list = False
    for i, line in enumerate(lines, 1):
        if TOP_LEVEL_KEY_RE.match(line):
            in_runtime_list = bool(RUNTIME_LIST_RE.match(line))
        elif in_runtime_list and not LIST_ENTRY_RE.match(line) and line.strip() and not line.strip().startswith("#"):
            in_runtime_list = False
        if in_runtime_list and re.match(r"^\s*- bootstrap/", line):
            problems.append(f"{name}:{i}: {line.strip()}")
    return problems


def verify() -> list[str]:
    """Check that no bootstrap/ refs remain in runtime lists (informational)."""
    problems = []
    for path in component_files():
        problems += scan_for_bootstrap(path.read_text().splitlines(),
                                       path.relative_to(COMPONENTS_DIR).as_posix())
    return problems


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true",
                        help="print what would change without writing files")
    args = parser.parse_args()

    print("== Generating new filter elements ==")
    for r in generate_filters(dry_run=args.dry_run):
        print(f"  {r}")

    print("\n== Rewriting components/ runtime dependencies ==")
    total = 0
    new_contents = {}
    for path in component_files():
        changes, new_lines = process_file(path, dry_run=args.dry_run)
        new_contents[path.relative_to(COMPONENTS_DIR).as_posix()] = new_lines
        for c in changes:
            print(f"  {c}")
            total += 1
    print(f"\n  {total} replacements "
          f"({'would be made' if args.dry_run else 'made'})")

    print("\n== Remaining bootstrap/ refs in runtime lists (should be empty) ==")
    if args.dry_run:
        # In dry-run mode, scan the post-replacement content in memory.
        problems = []
        for name, lines in new_contents.items():
            problems += scan_for_bootstrap(lines, name)
    else:
        problems = verify()
    if problems:
        for p in problems:
            print(f"  {p}")
        sys.exit(1)
    else:
        print("  (none)")


if __name__ == "__main__":
    main()
